// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGQFZALYz6yFUrpReQLhEE2cbfOZSK-Rg',
    appId: '1:876740242049:web:55bf651257915b2652bb80',
    messagingSenderId: '876740242049',
    projectId: 'assignment-373eb',
    authDomain: 'assignment-373eb.firebaseapp.com',
    storageBucket: 'assignment-373eb.firebasestorage.app',
    measurementId: 'G-ZQVP5PQDHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJExmHEKnyD9sf86IOHBIRTeX0fZQzcoM',
    appId: '1:876740242049:android:564a1e8da932834f52bb80',
    messagingSenderId: '876740242049',
    projectId: 'assignment-373eb',
    storageBucket: 'assignment-373eb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyedaL9JCW1vl8Go47QonGordzPlI6zE',
    appId: '1:876740242049:ios:4110eeb782b2c33252bb80',
    messagingSenderId: '876740242049',
    projectId: 'assignment-373eb',
    storageBucket: 'assignment-373eb.firebasestorage.app',
    androidClientId: '876740242049-t8qmrf5scj886nd8rt086se5unfqn0mv.apps.googleusercontent.com',
    iosClientId: '876740242049-8d5sejots7d50oqgn09mn43u93b8koo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ain',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyedaL9JCW1vl8Go47QonGordzPlI6zE',
    appId: '1:876740242049:ios:4110eeb782b2c33252bb80',
    messagingSenderId: '876740242049',
    projectId: 'assignment-373eb',
    storageBucket: 'assignment-373eb.firebasestorage.app',
    androidClientId: '876740242049-t8qmrf5scj886nd8rt086se5unfqn0mv.apps.googleusercontent.com',
    iosClientId: '876740242049-8d5sejots7d50oqgn09mn43u93b8koo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGQFZALYz6yFUrpReQLhEE2cbfOZSK-Rg',
    appId: '1:876740242049:web:7d104fd80fcbc43d52bb80',
    messagingSenderId: '876740242049',
    projectId: 'assignment-373eb',
    authDomain: 'assignment-373eb.firebaseapp.com',
    storageBucket: 'assignment-373eb.firebasestorage.app',
    measurementId: 'G-PBBWLCF6S7',
  );
}
